from fpdf import FPDF, XPos, YPos
from datetime import datetime

class PDF(FPDF):
    def header(self):
        # Logo
        import os
        current_dir = os.path.dirname(os.path.abspath(__file__))
        logo_path = os.path.normpath(os.path.join(current_dir, '..', 'templates', 'assets', 'apple-touch-icon.png'))
        self.image(logo_path, 10, 8, 20) # Smaller logo
        # Set font for title
        self.set_font('Helvetica', 'B', 18)
        # Title (centered, no border)
        self.cell(0, 10, 'Rent Invoice', border=0, align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        # Line break
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        # "Generated by HomeHive" on the left
        self.cell(0, 10, 'Generated by HomeHive', border=0, align='L', new_x=XPos.RIGHT, new_y=YPos.TOP)
        # Page number on the right
        self.cell(0, 10, f'Page {self.page_no()}', border=0, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)

def create_invoice_pdf(tenant_info: dict) -> tuple[bytes, str]:
    """
    Creates a consolidated rent invoice PDF for the tenant.
    `tenant_info` should be a dict with keys 'tenant_info' (containing 'name', 'email', 'mobileNumber', 'tenant_id')
    and 'due_rentals' (a list where each item has 'property_name', 'rent_amount', 'dueDate', 'payment_id').
    
    Returns a tuple containing the PDF bytes and the invoice number.
    """
    pdf = PDF()
    pdf.add_page()
    pdf.set_font('Helvetica', '', 12)

    # Extract tenant details from the nested 'tenant_info'
    tenant_details = tenant_info.get('tenant_info', {})
    tenant_name = tenant_details.get('name', 'N/A')
    tenant_id = tenant_details.get('tenant_id', 'UNKNOWN') # Define tenant_id here

    # Invoice Info
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_x(10)
    pdf.cell(95, 10, f"Bill To: {tenant_name}", border=0, align='L', new_x=XPos.RIGHT, new_y=YPos.TOP)
    
    # Extract the due date from the first rental for the invoice ID
    # Assuming all due_rentals for a consolidated invoice have the same dueDate
    first_rental_due_date_str = tenant_info.get('due_rentals', [{}])[0].get('dueDate', datetime.now().strftime('%d/%m/%Y'))
    try:
        invoice_date_component = datetime.strptime(first_rental_due_date_str, '%d/%m/%Y').strftime('%Y%m%d')
    except (ValueError, TypeError):
        invoice_date_component = datetime.now().strftime('%Y%m%d') # Fallback to creation date if parsing fails

    invoice_number = f"INV-{tenant_id[:8].upper()}-{invoice_date_component}"
    pdf.cell(95, 10, f"Invoice #: {invoice_number}", border=0, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font('Helvetica', '', 12)
    pdf.ln(10) # Add a line break for spacing

    # Invoice Date (right aligned)
    pdf.cell(0, 7, f"Invoice Date: {datetime.now().strftime('%Y-%m-%d')}", border=0, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    # The due date will be derived from the rentals list
    pdf.ln(10)

    # Invoice Table Header
    pdf.set_fill_color(200, 220, 255)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(90, 10, 'Description', border=1, align='L', fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(40, 10, 'Property', border=1, align='L', fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(30, 10, 'Due Date', border=1, align='C', fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(30, 10, 'Amount', border=1, align='R', fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Invoice Table Body
    pdf.set_font('Helvetica', '', 12)
    total_amount_due = 0.0
    for rental in tenant_info.get('due_rentals', []):
        description = f"Rent Payment for {rental.get('property_name', 'N/A')}" # Updated description
        property_name = rental.get('property_name', 'N/A')
        due_date = rental.get('dueDate', 'N/A')
        rent_amount = rental.get('rent_amount', 0.0)
        
        pdf.cell(90, 10, description, border=1, align='L', new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.cell(40, 10, property_name, border=1, align='L', new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.cell(30, 10, due_date, border=1, align='C', new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.cell(30, 10, f'ZMW {rent_amount:.2f}', border=1, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        total_amount_due += float(rent_amount)
    
    pdf.ln(10)

    # Total
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(160, 10, 'Total Amount Due:', border=0, align='R', new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(30, 10, f'ZMW {total_amount_due:.2f}', border=1, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    return bytes(pdf.output()), invoice_number
