from fpdf import FPDF, XPos, YPos
from datetime import datetime

class PDF(FPDF):
    def header(self):
        # Logo
        import os
        current_dir = os.path.dirname(os.path.abspath(__file__))
        logo_path = os.path.normpath(os.path.join(current_dir, '..', 'templates', 'assets', 'apple-touch-icon.png'))
        self.image(logo_path, 10, 8, 20) # Smaller logo
        # Set font for title
        self.set_font('Helvetica', 'B', 18)
        # Title (centered, no border)
        self.cell(0, 10, 'Rent Invoice', border=0, align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        # Line break
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        # "Generated by HomeHive" on the left
        self.cell(0, 10, 'Generated by HomeHive', border=0, align='L', new_x=XPos.RIGHT, new_y=YPos.TOP)
        # Page number on the right
        self.cell(0, 10, f'Page {self.page_no()}', border=0, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)

def create_invoice_pdf(tenant_info: dict) -> bytes:
    """
    Creates a consolidated rent invoice PDF for the tenant.
    `tenant_info` should contain 'name', 'email', 'mobileNumber', and a 'due_rentals' list.
    Each item in 'due_rentals' should have 'property_name', 'rent_amount', 'dueDate', 'payment_id'.
    """
    pdf = PDF()
    pdf.add_page()
    pdf.set_font('Helvetica', '', 12)

    # Invoice Info
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_x(10)
    pdf.cell(95, 10, f"Bill To: {tenant_info.get('name', 'N/A')}", border=0, align='L', new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(95, 10, f"Invoice #: Consolidated Invoice", border=0, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font('Helvetica', '', 12)
    pdf.ln(10) # Add a line break for spacing

    # Invoice Date (right aligned)
    pdf.cell(0, 7, f"Invoice Date: {datetime.now().strftime('%Y-%m-%d')}", border=0, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    # The due date will be derived from the rentals list
    pdf.ln(10)

    # Invoice Table Header
    pdf.set_fill_color(200, 220, 255)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(90, 10, 'Description', border=1, align='L', fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(40, 10, 'Property', border=1, align='L', fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(30, 10, 'Due Date', border=1, align='C', fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(30, 10, 'Amount', border=1, align='R', fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Invoice Table Body
    pdf.set_font('Helvetica', '', 12)
    total_amount_due = 0.0
    for rental in tenant_info.get('due_rentals', []):
        description = f"Rent Payment ({rental.get('payment_id', 'N/A')})"
        property_name = rental.get('property_name', 'N/A')
        due_date = rental.get('dueDate', 'N/A')
        rent_amount = rental.get('rent_amount', 0.0)
        
        pdf.cell(90, 10, description, border=1, align='L', new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.cell(40, 10, property_name, border=1, align='L', new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.cell(30, 10, due_date, border=1, align='C', new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.cell(30, 10, f'ZMW {rent_amount:.2f}', border=1, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        total_amount_due += float(rent_amount)
    
    pdf.ln(10)

    # Total
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(160, 10, 'Total Amount Due:', border=0, align='R', new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(30, 10, f'ZMW {total_amount_due:.2f}', border=1, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    return pdf.output()
