from fpdf import FPDF, XPos, YPos
from datetime import datetime

class PDF(FPDF):
    def header(self):
        # Logo
        import os
        current_dir = os.path.dirname(os.path.abspath(__file__))
        logo_path = os.path.normpath(os.path.join(current_dir, '..', 'templates', 'assets', 'apple-touch-icon.png'))
        self.image(logo_path, 10, 8, 20) # Smaller logo
        # Set font for title
        self.set_font('Helvetica', 'B', 18)
        # Title (centered, no border)
        self.cell(0, 10, 'Rent Invoice', border=0, align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        # Line break
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        # "Generated by HomeHive" on the left
        self.cell(0, 10, 'Generated by HomeHive', border=0, align='L', new_x=XPos.RIGHT, new_y=YPos.TOP)
        # Page number on the right
        self.cell(0, 10, f'Page {self.page_no()}', border=0, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)

def create_invoice_pdf(tenant_info: dict) -> bytes:
    """
    Creates a rent invoice PDF for the tenant in a standard format.
    """
    pdf = PDF()
    pdf.add_page()
    pdf.set_font('Helvetica', '', 12)

    pdf.set_font('Helvetica', '', 12)

    # Invoice Info
    pdf.set_font('Helvetica', 'B', 12)
    # Bill To (left aligned)
    pdf.set_x(10)
    pdf.cell(95, 10, f"Bill To: {tenant_info.get('name', 'N/A')}", border=0, align='L', new_x=XPos.RIGHT, new_y=YPos.TOP)
    # Invoice # (right aligned)
    pdf.cell(95, 10, f"Invoice #: {tenant_info.get('payment_id', 'N/A')}", border=0, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font('Helvetica', '', 12)
    pdf.ln(10) # Add a line break for spacing

    # Invoice Date (right aligned)
    pdf.cell(0, 7, f"Invoice Date: {datetime.now().strftime('%Y-%m-%d')}", border=0, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    # Due Date (right aligned)
    pdf.cell(0, 7, f"Due Date: {tenant_info.get('dueDate', 'N/A')}", border=0, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(10)

    # Invoice Table Header
    pdf.set_fill_color(200, 220, 255)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(130, 10, 'Description', border=1, align='L', fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(30, 10, 'Quantity', border=1, align='C', fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(30, 10, 'Total', border=1, align='R', fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Invoice Table Body
    pdf.set_font('Helvetica', '', 12)
    rent_amount = tenant_info.get('rent_amount', 1000.00) # Placeholder
    pdf.cell(130, 10, f"Rent for {tenant_info.get('property_name', 'N/A')} - Due {tenant_info.get('dueDate', 'N/A')}", border=1, align='L', new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(30, 10, '1', border=1, align='C', new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(30, 10, f'ZMW {rent_amount:.2f}', border=1, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.ln(10)

    # Total
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(160, 10, 'Total Amount Due:', border=0, align='R', new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(30, 10, f'ZMW {rent_amount:.2f}', border=1, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    return pdf.output()
