from fpdf import FPDF, XPos, YPos
from datetime import datetime
import os

class PDF(FPDF):
    def header(self):
        # Logo
        current_dir = os.path.dirname(os.path.abspath(__file__))
        logo_path = os.path.normpath(os.path.join(current_dir, '..', 'templates', 'assets', 'apple-touch-icon.png'))
        self.image(logo_path, 10, 8, 20) # Smaller logo
        # Set font for title
        self.set_font('Helvetica', 'B', 18)
        # Title (centered, no border)
        self.cell(0, 10, 'Receipt', border=0, align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        # Line break
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        # "Generated by HomeHive" on the left
        self.cell(0, 10, 'Generated by HomeHive', border=0, align='L', new_x=XPos.RIGHT, new_y=YPos.TOP)
        # Page number on the right
        self.cell(0, 10, f'Page {self.page_no()}', border=0, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)

def generate_receipt_pdf(data):
    """
    Generates a receipt PDF from the given data.
    """
    pdf = PDF()
    pdf.add_page()
    pdf.set_font('Helvetica', '', 12)

    # Receipt Info
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_x(10)
    pdf.cell(95, 10, f"Bill To: {data['tenant_name']}", border=0, align='L', new_x=XPos.RIGHT, new_y=YPos.TOP)
    
    receipt_number = f"RCPT-{data.get('payment_id', 'UNKNOWN')[-5:].upper()}-{datetime.now().strftime('%Y%m%d')}"
    pdf.cell(95, 10, f"Receipt #: {receipt_number}", border=0, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font('Helvetica', '', 12)
    pdf.ln(10) # Add a line break for spacing

    # Dates (right aligned)
    pdf.cell(0, 7, f"Date Paid: {data['date_paid']}", border=0, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(10)

    # Invoice Table Header
    pdf.set_fill_color(200, 220, 255)
    pdf.set_font('Helvetica', 'B', 12)
    col_widths = {'desc': 40, 'prop': 110, 'amt': 40} # Adjusted widths
    pdf.cell(col_widths['desc'], 10, 'Description', border=1, align='L', fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(col_widths['prop'], 10, 'Property', border=1, align='L', fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(col_widths['amt'], 10, 'Amount', border=1, align='R', fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Invoice Table Body
    pdf.set_font('Helvetica', '', 12)
    property_name = data.get('property_name', 'N/A')
    items = data.get('additional_info')

    if not items:
        items = [{'amount': data.get('amount_paid', 0.0)}]

    for item in items:
        description = "Rent" # Changed as per request
        
        # --- Calculate row height ---
        desc_lines = pdf.multi_cell(col_widths['desc'], 10, description, split_only=True)
        h_desc = len(desc_lines) * 10

        prop_lines = pdf.multi_cell(col_widths['prop'], 10, property_name, split_only=True)
        h_prop = len(prop_lines) * 10

        row_height = max(h_desc, h_prop, 10)

        # --- Draw cells with calculated height ---
        pdf.multi_cell(col_widths['desc'], row_height, description, border=1, align='L', new_x="RIGHT", new_y="TOP")
        
        pdf.multi_cell(col_widths['prop'], row_height, property_name, border=1, align='L', new_x="RIGHT", new_y="TOP")
        
        pdf.cell(col_widths['amt'], row_height, f"ZMW {item.get('amount', 0.0):.2f}", border=1, align='R', new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(10)

    # Total
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(150, 10, 'Total Paid:', border=0, align='R', new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(40, 10, f"ZMW {data['amount_paid']:.2f}", border=1, align='R', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.ln(20)

    # Thank you message
    pdf.set_font("helvetica", "I", 12)
    pdf.cell(0, 10, "Thank you for your payment!", ln=True, align="C")

    return bytes(pdf.output())